add support for wikipedia, readthedocs, cnblogs, etc. ; add keyboard shortcut: alt+t
hikerpig/toc-bar-userscript pull request #12
Opened 2022-04-16 15:00 UTC by RichardBaker3020

add support for wikipedia, readthedocs, cnblogs, etc. ; add keyboard shortcut for toggling: alt+t

2022-04-16 16:17 UTC, hikerpig requested changes
Thank you for this PR !
But I have some little questions, followed by the comments.

2022-04-16 16:17 UTC, hikerpig commented on toc-bar.user.js
> +      document.addEventListener('keydown', function(e) {
I'm afraid this is too intrusive for the user.
Can we use some of GM or violent monkey's shortcut feature (if there is any) so the user can see and change this shortcut ?

2022-04-16 16:17 UTC, hikerpig commented on toc-bar.user.js
> +  margin: auto;
What does this do?

2022-04-16 16:17 UTC, hikerpig commented on toc-bar.user.js
> +  font-family: 'Roboto';
I'm not sure if this should be added, or maybe it's not enough to add just one font-family

2022-04-16 16:17 UTC, hikerpig commented on toc-bar.user.js
> +  text-decoration: auto;
What will happen if we don't add this ?

2022-04-17 04:26 UTC, RichardBaker3020 commented
Currently tocbar might look differently on different sites :
 ![image](https://user-images.githubusercontent.com/54793121/163700218-fee5dd5a-5865-43fd-b488-8721f1cb17b7.png)
![image](https://user-images.githubusercontent.com/54793121/163700359-538681b6-5281-4c2a-939d-d7f85e5720f6.png)
![image](https://user-images.githubusercontent.com/54793121/163700375-23ccb86e-d9c2-429f-a1be-31c4dbecb523.png)

2022-04-17 12:34 UTC, hikerpig approved these changes
Appreciate your efforts 🙇‍♀️

2022-04-17 12:34 UTC, merged